### ISSUE TITLE
Deploy OVF wizard: vCenter credentials special characters

### ISSUE THREAD

**Issue by Kyleset** [vmware-samples/vcenter-event-broker-appliance#205]
When running through the OVF template deploy wizard for VEBA. You input the vCenter credentials. It doesn't appear to like *some* special characters. Not sure the total list but...

In this particular case, the password had & in it. In the /root/config/event-router-config.json file it substituted &amp; for &.

**Comment by kremerpatrick** [comment]
Github is rendering the character entity as the correct character, so it's not showing up as expected. But the problem that he's reporting is the HTML character entity ampersand-amp-semicolon is what shows up in the JSON file.

**Comment by embano1** [comment]
Another catch is the JSON [specification](https://www.freeformatter.com/json-escape.html) which requires certain characters to be properly escaped. Are we already doing this in the setup routine @lamw ?

**Comment by embano1** [comment]
https://twitter.com/embano1/status/1247169343806271500?s=20

**Comment by embano1** [comment]
@Kyleset which version of VEBA are you running?

**Comment by kremerpatrick** [comment]
Testing results: 
Fresh deploy of 0.4.1
![image](https://user-images.githubusercontent.com/29929717/95217215-8a43ad00-07b8-11eb-9eeb-6d3bc8e6096a.png)

Used ampersand+VMware1! as password for everything - vCenter, SSH, OpenFaaS.

Password fields in event-router-config are unescaped.
![image](https://user-images.githubusercontent.com/29929717/95217365-b52e0100-07b8-11eb-8a8c-fad2b2610a8e.png)

To access the appliance, I had to type in ampersand-amp-semicolon+VMware1! for both SSH and OpenFaaS UI. The event router fails to come up because the vCenter password is wrong.

**Comment by dsbibby** [comment]
@lamw @embano1 Happy to work on a fix for this if that's helpful?

**Comment by lamw** [comment]
@dsbibby Thanks. This was actually fixed awhile back, @kremerpatrick can you confirm?

**Comment by lamw** [comment]
Reference: https://github.com/vmware-samples/vcenter-event-broker-appliance/pull/104

**Comment by dsbibby** [comment]
@lamw - I hadn't spotted that! However, it looks like it was fixed for the event router, but what made me look is I got caught out by the appliance root password part of this.

My thought on how to approach a fix was to look at swapping out setup.sh for a python alternative that parsed the ovfEnv XML and then called each of the existing setup-xx scripts. That way the individual scripts wouldn't need to be concerned with escaping HTML entities directly.

**Comment by embano1** [comment]
@dsbibby this is likely caused during/right after OVF property parsing/conversion. @kremerpatrick and @lamw are looking into it.

**Comment by lamw** [comment]
@dsbibby Initial testing on vSphere 7.0 Update 1 via OVFTool, it looks like as part of the OVF deployment (this doesn't involve VEBA scripts) the special character is somehow transformed/escaped and hence why we're seeing it. I'll need to confirm that the vSphere UI has same behavior and then I'm going to see if we can repro on vSphere 6.7 to see if this a behavior change or something we've always had but doesn't seem to be related to VEBA since the initial issue was related to vSphere credentials not being escaped and was handle in #104 but its a good point about potentially escaping it in `setup.sh` and rest of the scripts don't need to worry about it

**Comment by dsbibby** [comment]
@lamw Yes - I did take a bit of a look to figure out why my password wasn't working. At the very least the issue seems to apply to all 5 of the XML [Predefined Entities](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML)

It would seem prudent to decode these 5 chars at least although I think I would use a full XML parser ideally. A quick spot of internet plagiarism found this python snippet which when I tried in an empty Photon VM seemed to handle the 5 XML Predefined Entities:
```import subprocess
from xml.dom.minidom import parseString
from pprint import pprint

ovfenv_cmd="/usr/bin/vmtoolsd --cmd 'info-get guestinfo.ovfEnv'"

def get_ovf_properties():
    """
        Return a dict of OVF properties in the ovfenv
    """
    properties = {}
    xml_parts = subprocess.Popen(ovfenv_cmd, shell=True,
                                 stdout=subprocess.PIPE).stdout.read()
        raw_data = parseString(xml_parts)
    for property in raw_data.getElementsByTagName('Property'):
        key, value = [ property.attributes['oe:key'].value,
                       property.attributes['oe:value'].value ]
        properties[key] = value
    return properties

pprint(get_ovf_properties())```
