### ISSUE TITLE
Include event filtering natively in VEBA

### ISSUE THREAD

**Issue by dsbibby** [vmware-samples/vcenter-event-broker-appliance#210]
**Is your feature request related to a problem? Please describe.**
Currently events are only filtered by event type - it would be great if filtering on each event could be performed to allow functions to only run for certain collections of VC objects or in reaction to very specific event details.

**Describe the solution you'd like**
This issue is here to discuss best ways to implement this. Ideally all config would be in the function's `stack.yml`.

**Describe alternatives you've considered**
There is now a function that allows for filtering of events before passing the cloud event data on to another function (function chaining), but it would be great if eventually this were a core part of VEBA rather than adding the complexity of chaining

**Additional context**

**Comment by embano1** [comment]
Thank you @dsbibby for bringing this up! This is a much requested functionality and I'm glad we can discuss a potential solution to this here.

Given the nature of VEBA/router, there's couple of places where filtering could be performed (which also impacts the user experience). Quick braindump:

- [1] At the event provider, e.g. filter at source (vCenter)
- [2] At the router, e.g. via providing filter rules (similar to AWS EventBridge `rules`)
- [3] At the processor, e.g. OpenFaaS, AWS EventBridge
- [4] At the function level (in case of FaaS processor)

**PROs/CONs of [1]:**
+++ Efficiency: Reduces load on the router/source due to source-based filtering
---  Global setting for the source (router), function author has no direct influence (would have to configure filtering outside of pure function logic)
--- Not all event providers might support server-side filtering

**PROs/CONs of [2]:**
+++ Configuration applies generically to all event providers/processors
+++ Multi-rules and complex filtering logic possible
--- Event(s) have to be processed by router, i.e. efficiency gains smaller compared to server-side filtering
--- Global setting(s) in the router, function author has no direct influence (would have to configure filtering outside of pure function logic)

**PROs/CONs of [3]:**
+++ Highly customizable since logic can be event provider specific
+++ Multi-rules and complex filtering logic possible
--- Event(s) have to be processed by router, i.e. efficiency gains smaller compared to server-side filtering
---  Global setting for the event provider, function author (FaaS) has no direct influence (would have to configure filtering outside of pure function logic)
--- Different implementation styles depending on the event processor, e.g. AWS vs knative vs OpenFaaS

**PROs/CONs of [4]:**
+++ Highly customizable since logic is per function
+++ Directly configurable by function author
--- Only applies to "FaaS-ish" frameworks
--- No efficiency gains
--- Often leads to complex function chaining logic (fn calls fn) likely leading to brittle implementations (error handling outside of the direct control of the event processor)

**Comment by dsbibby** [comment]
Thanks @embano1 for the summary of options.

From my own experience and use cases I think options 2 or 3 are possibly the best to explore.

Option 4 we have have now with the pre-filter example function (or at least will do when I finish the documentation and testing of my updated version!). This option is highly flexible and fits all our current needs, but as you rightly point out is somewhat more complex than it perhaps needs to be. I think I'm right in saying that this option isn't negated by the implementation of any of the other 3 options either and could remain for advanced use cases, but ideally a VEBA integrated option would cover 99% of use cases.

I've not dug deep enough in to the inner workings of the event router or indeed even tried to understand anything other than the OpenFaaS event processor as yet to really grasp how options 2 and 3 would differ in a final implementation. 

Perhaps an example of some user-stories here would help... here are two of ours:
### Case 1 - most typical example
#### Multiple types of events raised by a variety of objects, but limited to a single cluster trigger a single FaaS function
We need to trigger a single function whenever a variety of VM events and storage placement events occur, but constrained to objects within specific vCenter clusters.

### Case 2 - more advanced example
#### Multiple events with different filters triggering a single FaaS function
We need to run a single vRO workflow whenever a VM object within a specific cluster is:
1. created with encryption
2. has an existing disk encrypted
3. has an existing disk decrypted
Each of these events have a different combination of vCenter event type and filtering needs, so currently we have 3x separate "pre-filter" FaaS functions all calling the same vRO function to handle this.
