### ISSUE TITLE
Update scheme and add infromation about what is inside containers

### ISSUE THREAD

**Issue by dvolozhinok** [vmware-samples/vcenter-event-broker-appliance#548]
**Is your feature request related to a problem? Please describe.**
We want to tightly implement VEBA in a large infrastructure of a productive public cloud. But there is lack of schematics documentation. All we have is this scheme:
![veba-architecture](https://user-images.githubusercontent.com/74653910/128351119-62da20d7-6ab8-4326-b3ae-297e814a1b02.png)

**Describe the solution you'd like**
We need a more detailed scheme. Just an example of intensity of detail we want. Below is a scheme for another system just for example of detalisation. Please make such detailed scheme for VEBA so we can better understand it's architecture. And mark with different colors to show which containers are critical and which are created just for one job.
Please also add information which containers is important to monitor and which we don't need to monitor.
![Example scheme](https://user-images.githubusercontent.com/74653910/128351580-01d470a3-0151-4c15-a2fe-889df93642a0.png)

**Comment by lamw** [comment]
HI @dvolozhinok - Would you be able to share more details on the specific public cloud you intend to work with? Is this bare-metal / VM or K8s infrastructure? This is important because VEBA can be deployed as Virtual Appliance (which is what the hight level architecture diagram represents) but it can also be deployed to an existing K8s Cluster and many of the components we need for the appliance may not be applicable, for example Contour for Ingress or proper Service Load Balancer since you will have more than a single node. 

At the heart of VEBA, is the [VMware Event Router which can easily be deployed using Helm](https://github.com/vmware-samples/vcenter-event-broker-appliance/tree/development/vmware-event-router#option-2-configuration-with-knative) if you have an existing K8s Cluster. You of course will be required to setup the Knative infrastructure that VMware Event Router relies on. 

If you can provide some more details on your expected deployment, especially with the number of vCenter Server, etc. We can provide further guidance and see how this can be re-incorporated into our documentation.

**Comment by lamw** [comment]
If you're open, we'd love to chat in more detail over Zoom. Feel free to reach out to us dl-veba@vmware.com

**Comment by dvolozhinok** [comment]
>Would you be able to share more details on the specific public cloud you intend to work with? Is this bare-metal / VM or K8s infrastructure?

Bare metal on ESXi + vCenter. I think we'll continue at Zoom, since it public disclosure of company infrastructure information.
We can also deploy K8S cluster if needed.

> If you're open, we'd love to chat in more detail over Zoom. Feel free to reach out to us dl-veba@vmware.com

Sure.

**Comment by dvolozhinok** [comment]
Please approve my invitation.

**Comment by lamw** [comment]
> Please approve my invitation.

Sorry, which invitation? Did you send us an email?

**Comment by lamw** [comment]
@dvolozhinok Looks like our internal email system took awhile to process the Zoom invite. Please just send an email to that DL and we can find a slot that works for Zoom meeting. Sorry for the confusion as I didn't mean on meeting right then

**Comment by dvolozhinok** [comment]
@lamw what is DL? Can we schedule a meeting for August 10th?
![20210806105351_Zoom](https://user-images.githubusercontent.com/74653910/128476687-fd5aca9b-b99a-4672-a52f-ff5e1a175a1f.png)

**Comment by lamw** [comment]
DL = distribution list, which is the email address I had shared with you earlier so that you can reach out directly: dl-veba@vmware.com

Please send an email and we can figure out a time slot for 8/10
