### ISSUE TITLE
Integrate a notification service 

### ISSUE THREAD

**Issue by rhjensen79** [vmware-samples/vcenter-event-broker-appliance#550]
**Is your feature request related to a problem? Please describe.**
I saw a tweet from @lamw around telegram notifications, and remembered, seeing this "all in one" service, and thought this might be something, that was worth intrating into the product, to provide a easy to use, way of doing notifications, on different services.

**Describe the solution you'd like**
Integration of a notification service like this one : https://github.com/caronc/apprise

**Describe alternatives you've considered**
Always DIY :-) 

**Additional context**
Note not a real problem, but something that i thought could enhance an already cool solution.

**Comment by lamw** [comment]
Thanks for sharing the apprise solution, this is not something I've used before. It definitely can be useful for those wanting to integrate multiple "notification services" and could certainly be interesting from a VEBA function point of view, but it does add an additional dependency, which then needs to be further managed/etc. In addition, the guiding principal for FaaS-based solution is that each function is responsible for a single piece of business logic and although this could be used to satisfy multiple services, it does violate that to a certain degree.

**Comment by rhjensen79** [comment]
Interesting views, i did not think of.
Could a potential solution here, be a sidecar (container), to the function, that get's a central config (like auth keys etc. ) when run. Or am i just digging an even bigger hole here :-) 

A whole other option, is a second ova, with apprise, for easy deployment, that could benefit if people wan't solutions like that. 

No matter what, i have no need for the usecase, it was just your twitter post, that got me thinking. So maybe something, for when/if the demand occurs :-)

**Comment by lamw** [comment]
> Could a potential solution here, be a sidecar (container), to the function, that get's a central config (like auth keys etc. ) when run.

Well, this already exists with the current implementation, you (function author) can define what you want in that file which is then stored as a k8s secret and is made available to your function. If you can abstract across all those services to define high level input params, then you could certainly do what you're describing OR just have an uber config that has all the variables and then you handle checking which is filled out to determine the correct notification service to use. Its surely possible but a lot of error handling for potential use of other/mix notification service and you can see why its not ideal to keep it too generic 

> Or am i just digging an even bigger hole here :-)

Its a good discussion, but I do feel this is probably a solution to a problem that may not exists for most folks :) In practice, I see one to two NS being used by customers and they normally will have different formats or users they wish to notify, so it may end up being easier to just have two functions that is purpose built rather than keeping it generic. 

My 2cents

**Comment by rhjensen79** [comment]
I do agree on the last part :-) 

I will close the issue. 
Thanks for the feedback :-)

**Comment by embano1** [comment]
Just adding some thoughts here (even this issue is closed). When I was looking at a generic webhook implementation for the event router piece, I was also considering using a solution/service which offers multiple endpoints/implementations in a generic manner instead of writing a "provider" for each use case. However, as William said, not only does this offer another dependency (which has to be maintained and might not be usable by every user), but there would still be cases which a generic solution can't offer (e.g. custom logic, etc.).

So the general pattern here is to either extend VEBA with your own service (remember, VEBA ships with Knative, so you could easily write your own custom service for this) or create functions per use case.

On the latter, @pksrc built something based on the previous platform we used (OpenFaaS) which does exactly this for REST based APIs: https://github.com/vmware-samples/vcenter-event-broker-appliance/tree/development/examples/openfaas/python/invoke-rest-api
