### ISSUE TITLE
I need help with the output of information through HTTP from my deployment with a function. 

### ISSUE THREAD

**Issue by it-podshivalov** [vmware-samples/vcenter-event-broker-appliance#558]
Hello friends!

I have knative veba installation. 
My fuction is based on kn-pcli-tag example.
I'd like a function that took informations from VC when happen HA event, and put a file with this information in the HTTP directory in the same POD. And this file must be available on http from external network.
I ran into a problem with port forwarding.

I tried to create NodePort service, and I got access to my internal http service, but throught 32*** random port, but I need available to 80 port. 

I know that I should to setup it throught envoy, but I could not understand how to do it. I'm not very strong in k8s)

Help me please)

**Comment by embano1** [comment]
Hi @it-podshivalov and thx for using VEBA! My feeling is that somehow this sounds like an anti-pattern and I'd love to learn more about your use case/requirements before going down the route you're proposing (since functions are stateless).

**Comment by it-podshivalov** [comment]
> 
> 
> Hi @it-podshivalov and thx for using VEBA! My feeling is that somehow this sounds like an anti-pattern and I'd love to learn more about your use case/requirements before going down the route you're proposing (since functions are stateless).

Hi @embano1, thanks for fast reaction! 
My case :
We are service provider. Sometime heppens events that needed fast reaction, such as HA events or our customer has created an oversized disk on their VM and we need inform him about this or other important events. 
Consider HA event. 
When happens HA event, We need to immediately find out which VMs were rebooted in order to notify customers. We also need to find out on which hypervisors they started because we need check VMs, also we need push this infomtions on our CNDB for history and analizes. And all this must be automated. 

I think the VEBA is perfect for solving my case.
My steps:
1. I deploy VEBA in my test VCSA 7 infrastructure. 
2. I check that VEBA is work, I run powercli kn-pcli-tag example, all fine.
3. So, I redesigned the function so that it creates a json file with the information I need(for my test it's just VM name). I have't configured the trigger yet. While it's 'DrsVmPoweredOnEvent'.
4. I install and run httpd in the same pod where my function is running. 
5. In my function, I output the file _$vmName | ConvertTo-json | Out-File ./etc/httpd/html/out.json_
6. I make sure the file is available I run on my pod  _curl localhost/out.json_ and all fine.

So, I want to get access to this file from external service, for example from my CNDB, it's also VM in other insfrustructure place and other network, which has network connectivity on port 80 with the network where the VEBA is located 
To do this, I must learn to provide access to my file inside the module from the outside on port 80. 

P.S. Sorry for my English)

**Comment by embano1** [comment]
Thx for the detailed response! Now that I have a better understanding of your use case, let me suggest a different approach (which is generally preferred/considered best practice in async, stateless event-driven systems).

Functions (Knative Services) are generally considered stateless, i.e. should not/do not persist state. That means, that your container(s) (pods) could be restarted or auto-scaled anytime and thus lose state. Storing a JSON file inside a function will not persist that file over reboots. Container orchestrators like Kubernetes were built for stateless systems and later got support for running complex stateful workloads (StatefulSet). Knative sits in the middle here, where it is tailored towards stateless web services (e.g. functions).

This is actually considered a benefit as stateless systems are usually easier to build, scale, and reason about (troubleshoot). 

So instead of having CMDBs or other actors calling your function (HTTP) to retrieve information, this information (restarted VMs) should be sent by the function to an external (durable) state store (DB, CMDB, FTP, eMail, etc.). 

The message broker inside VEBA persists events and retries their delivery (up to a threshold) to individual functions (via triggers). The function is then responsible for:

a) performing its business logic (e.g. send alert eMail with restarted VMs) and
b) acknowledge the event to the broker so the broker won't redeliver it again

Part (b) is automatically handled by your function when it successfully returns from the handler, i.e. without throwing an exception.

Since operations (a) and (b) are not atomic, i.e. your function can crash right in the middle, your function might be involved multiple times for the same event and has to be build with idempotence in mind.

Here's some more background information (applies beyond AWS Lambda): https://aws.amazon.com/premiumsupport/knowledge-center/lambda-function-idempotent/

Let me know if this helps and I'm happy to provide more information. Also feel free to join our Slack channel to have further discussions on this topic.

> P.S. Sorry for my English

No need to excuse and I fully understood your question! Discloser: non-native writer here as well ;)

**Comment by it-podshivalov** [comment]
Hello Dear @embano1

I understud your message. And I started to thinking in this direction.
I need that a file with my data will be saved outside of the pod. 
For this I decided to create a persistentVolume
![изображение](https://user-images.githubusercontent.com/57752592/133080743-85ec2a2a-9777-4b43-aada-a98be4fa7c30.png)
persistentVolume is created, all fine.
And than I create PersistentVolumeClaim
![изображение](https://user-images.githubusercontent.com/57752592/133080814-d54bb703-f8df-4b60-909b-947ea4f9ca3a.png)
However, I get status Pending
![изображение](https://user-images.githubusercontent.com/57752592/133080665-1e9f9c9c-7ba0-4e52-b6b2-1beb0bfd4186.png)
I try to mount the persistentVolume, but I get a error when I try to apply my deployment. 
![изображение](https://user-images.githubusercontent.com/57752592/133079851-8716a8f9-e426-47ba-9da9-864dfc89978c.png)
![изображение](https://user-images.githubusercontent.com/57752592/133079867-78348ae5-9bd5-4d8c-950f-068e93ea06c3.png)

Maybe there is a smarter way to save my data outside of the pod.
I would be very grateful if you would guide me on the path of truth :)

**Comment by embano1** [comment]
VEBA and its internal function runtime knative is not designed for this use case (https://github.com/knative/serving/issues/2025) and thus you have to heavily change your application and hack VEBA's Kubernetes installation to make this work. 

However, I strongly advise against it since, as I wrote in the previous reply, this I'd consider this an anti-pattern for the use case you described.

Is there no external datastore, database, bucket, server, etc. that you can use here?

**Comment by it-podshivalov** [comment]
> 
> 
> VEBA and its internal function runtime knative is not designed for this use case ([knative/serving#2025](https://github.com/knative/serving/issues/2025)) and thus you have to heavily change your application and hack VEBA's Kubernetes installation to make this work.
> 
> However, I strongly advise against it since, as I wrote in the previous reply, this I'd consider this an anti-pattern for the use case you described.
> 
> Is there no external datastore, database, bucket, server, etc. that you can use here?

Dear @embano1 
Thank you for help.

I decided my case using an external FTP server.
