### ISSUE TITLE
Plugin Model for Outbound Webhooks

### ISSUE THREAD

**Issue by BlueArcherX** [vmware-samples/vcenter-event-broker-appliance#6]
After reviewing the work done by @opvizordz in https://github.com/vmware-samples/vcenter-event-broker-appliance/pull/5/commits/b35a3e2b2e1d783f7ee399a621c21d8e7b06ffe8, it occured to me that it may be worth exploring a plugin model for the outbound webhooks.  This will let anyone contribute a plugin for their chat platform of choice, and any new functions could re-use this code.

I am probably not the right person to implement the framework, but I could contribute some plugins.

**Suggestions:**
- Microsoft Teams
- WebEx Teams
- Discord
- Telegram
- ???

We use WebEx Teams at work and I could test my home lab against Discord, so I could potentially work on those.

**Comment by embano1** [comment]
Thank you @BlueArcherX for your idea. Are you alluding to a language-specific framework, e.g. PowerShell/CLI? I'm not a PCLI expert, so would let @lamw jump in and elaborate on its feasibility.

**Comment by opvizordz** [comment]
Thx @BlueArcherX - I think most of the platforms could be addressed the in a similar way, sending a POST to a Webhook  (`Invoke-RestMethod -Method Post`) instead of a module for each one (as I did with PSSlack).
What I found as a starting point so far:
MS Teams: http://mikeconjoice.com/2018/05/25/send-a-notification-to-microsoft-teams-via-powershell/
WebEx Teams: https://matthewfugel.wordpress.com/2018/11/09/posting-to-cisco-webex-teams-via-powershell/
Discord: https://github.com/EvotecIT/PSDiscord

I didn't find any Powershell project that combined all of them and offered general functions. Are you aware of any?

**Comment by lamw** [comment]
I agree with @opvizordz, I'm not aware of any particular PS project which attempts to combine the various chat platforms but if they all support Webhooks, you can certainly make a generic function which handles the type of platform, webhook URL and the payload requests.

**Comment by BlueArcherX** [comment]
Sorry, folks, I was travelling out of town and just got home.

I probably did not elaborate on this request quite enough to make sense to others.  I guess in my mind, I had envisioned something [like this project](https://github.com/vmw-loginsight/webhook-shims) (see plugins in loginsightwebhookdemo directory) that we played with a year or two ago in order to shim vROps outbound REST notifications to our Webex Teams instance.

Maybe it being baked in to the VEBA project itself is the wrong idea, but my intention was to allow for a way to separate the functions actually doing the event processing from the outbound webhook calls (and the logic for the multitude of chat platforms).  If the VEBA project could develop/include a fairly fleshed out webhook function with plugins for different chat tools, then it frees up people to focus on building event handlers and not figuring out how to re-invent an interface to their chat platform that someone else probably already did.

Just trying to provide a bit of value-add out of the box to get people up and running quickly for chatops.

**Comment by embano1** [comment]
Is my understanding correct that if we provide a function that:

1) let's a user define the triggered event(s), e.g. `vm.powered.on` and
2) accepts two parameters for `remoteURL` and `token`

...then users could use that function to forward events to any supported webhook (`remoteURL` and `token`) because the function contains the logic for constructing the right payload for the corresponding webhook, e.g. Teams or Slack?

I think that's possible, but on the other hand it also becomes an "uber" function where we would violate the "single responsibility principle" (which in this case can be debated).

**Comment by pksrc** [comment]
Is this covered by the Rest API fn? https://github.com/vmware-samples/vcenter-event-broker-appliance/tree/development/examples/python/invoke-rest-api
Hopefully no principles were violated :)
