### ISSUE TITLE
Deployment and vCenter username

### ISSUE THREAD

**Issue by rkt6865** [vmware-samples/vcenter-event-broker-appliance#79]
When entering the vCenter username during deployment and the vCenter username is a domain user, you must use either of the following two formats:

  username@domain.abc
  domain\\username  (2 backslashes)

If "doman\username" format is entered, the vmware-event-router pod will fail to start.

Backslash must be replaced with \\ in JSON

**Comment by embano1** [comment]
@lamw 
This is also true for all other variables used in the JSON file used by the `vmware event router`. I suggest correctly escaping those values before passing into the JSON file. Do we have Python installed in the appliance build/deployment environment to simplify this? Otherwise this would be a `BASH` one-liner to at least handle `\` correctly (but there are [more](https://www.freeformatter.com/json-escape.html) special JSON characters).

```bash
VARIABLE=${VARIABLE//\\/\\\\} # escape \ in $VARIABLE
```
