### ISSUE TITLE
Broken link in manual deployment instructions

### ISSUE THREAD

**Issue by kremerpatrick** [vmware-samples/vcenter-event-broker-appliance#861]
http://vmweventbroker.io/kb/event-router#manual-deployment

"Use one of the configuration files provided [here](http://vmweventbroker.io/kb/deploy/)" - link results in a 404.

**Comment by embano1** [comment]
Hm, just looked into that and there's a problem: the reason why this throws a 404 is because it's a relative link on the Github README. The website interprets it as a relative link too, but using the base domain instead of Github.

Not sure how we can resolve this instead of manually hardcoding the values. The latter is error-prone and always gets overwritten if we make changes to the Router documentation. Changing this in the router documentation (Github) also is not a good idea because we have to use absolute refs now. Hm...
