### ISSUE TITLE
Create Helm chart for Event Router

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#97]
Make it easier for users deploying vmware-event-router directly (on Kubernetes) by providing a Helm chart.Evaluate options for air-gapped deployments.

**Comment by lamw** [comment]
Based on a discussion with @embano1 regarding some of the challenges with Helm chart (related to JSON/YAML) and also from a timing standpoint. It has been decided that we'll create a simple shell script to help customers who wish to deploy VEBA to an existing K8s Cluster rather than creating a Helm chart.
